name: 🚀 Deploy to Production
on:
  release:
    types: [released]
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - run: sam build --use-container
        working-directory: ./apps/history-generator
      
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name history-generator --resolve-s3 --capabilities CAPABILITY_IAM
        working-directory: ./apps/history-generator
