name: 🚀 Deploy to Production
on:
  release:
    types: [released]
jobs:
  lambda-deploy:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: "install deps"
        run: npm i
        working-directory: ./apps/history-generator
  
      - name: "build app"
        working-directory: ./apps/history-generator
        run: npm run build

      - name: default deploy
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: cryptoPriceHistoryGenerator
          source: ./apps/history-generator/dist/index.js

          
  beanstalk-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v4
      
        
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: "install deps"
      run: npm i
      working-directory: ./apps/backend

    - name: "build app"
      working-directory: ./apps/backend
      run: npm run build

    - name: Generate deployment package
      working-directory: ./apps/backend/dist
      run: zip -r app.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: eu-north-1
        application_name: bilira-crypto-app
        environment_name: Bilira-crypto-app-env
        version_label: ${{ github.event.release.tag_name }}
        deployment_package: ./apps/backend/dist/app.zip
