name: 🚀 Deploy to Production
on:
  release:
    types: [released]
jobs:
  deploy:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: "install deps"
        run: npm i
        working-directory: ./apps/history-generator
  
      - name: 🔎 Type check
        working-directory: ./apps/history-generator
        run: npm run build

      - name: default deploy
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: gorush
          source: ./apps/history-generator/dist/index.js
